### ISSUE TITLE
Having trouble running the sample in multitenant mode.

### ISSUE THREAD

**Issue by cephalin** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#10]
-	VS2013.4: The sample page says that it can be run in any tenant, but when I run the sample locally and log in with xxx@hotmail.com, I get this error:
Additional technical information:
Correlation ID: 0c3e4797-929e-47ed-9fd7-309e3e084e94
Timestamp: 2015-09-30 21:45:28Z
AADSTS50020: User account 'xxx@hotmail.com' from external identity provider 'live.com' is not supported for application 'd43fe016-2ce2-4686-ad31-9169be137d72'. The account needs to be added as an external user in the tenant. Please sign out and sign in again with an Azure Active Directory user account.
-	VS2015: The HTTPS link won’t even work when I tried to test it locally.

Any ideas?

**Comment by dstrockis** [comment]
Did you add your hotmail account as a guest user in your tenant?

**Comment by dstrockis** [comment]
Also by request, I meant the HTTP request that is sent to Azure AD.  You can find it by copy+pasting it out of the URL bar before attempting to sign in, or by capturing a trace in Fiddler or similar

**Comment by cephalin** [comment]
I'm using the application in its default configuration, trying to use the multitenant mode. The user I used to sign in with is the service administrator of my default AAD tenant, so I don't need to add it as a guest account, right? The instructions don't say anything about adding a guest account.

**Comment by cephalin** [comment]
The URL at the sign-in page is: https://login.microsoftonline.com/common/oauth2/authorize?client_id=d43fe016-2ce2-4686-ad31-9169be137d72&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dwpZT0M3Mz3WQWeGrH8rpkAAz2fDFaQVX4kZKqjl26c0SDWZLVa0pVU0pj-lv9oKAdvYMjS3RDM00lokMGVSANPftTEYLY8bJQNjWAixGFkw&nonce=635794053963374959.NjMyYzQ3NWEtNDQzNi00Yzc1LWE1NzQtZGQwMzg4ZmE1YWJkNjQ5NzM5NmUtMzllZi00M2JlLThiM2EtNjJkY2Q1NDYwOTZh

**Comment by dstrockis** [comment]
To confirm - which tenant is the application registered in?

**Comment by cephalin** [comment]
If I use the default settings, I suppose the application is registered in the Microsoft tenant, right?

**Comment by dstrockis** [comment]
Ohhhhh I totally forgot that this app already has default settings. My fault.  Ok no, the default app is registered in my own tenant actually.  I get it now.

MSA guest account users will not work with multi-tenant apps.  Your MSA user could be a guest in N AAD tenants - and when the sign in request goes to the `/common` endpoint, AAD cannot determine which tenant to sign the user into.  That's why you get that error.  If you sign into the app with a work account in your tenant, it should work fine.

I'll add a comment to the readme about MSA users not being supported.

**Comment by dstrockis** [comment]
a38ded23d9122a8b7662bb4e306aff12c6199c6f

**Comment by dstrockis** [comment]
If you try it and it works, please close the issue.

**Comment by cephalin** [comment]
It works now. Thanks!
