### ISSUE TITLE
Roles aren't being picked up

### ISSUE THREAD

**Issue by franhoey** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#14]
I feel like I must be missing something important, but I just cant see it

I've followed your instructions for the single tenant but I keep getting "You do not have sufficient priviliges to view this page." when I go to the tasks root. I've set it up twice now in two different azure accounts but still no luck

I've create a new user and assigned them to the Observer role, logged out and back in, but no luck. 

The only step I wasn't sure about was the App ID URI, my tenant is the default "Default Directory", should the uri be "https://default_directory/tasktrackerwebapp"? Does it actually matter? 

What can I do to debug the problem?

Thanks,
Fran

**Comment by franhoey** [comment]
This is an issue in the single tenant instructions, only the `ValidateIssuer' line should be deleted in `TokenValidationParameters` not the whole block.

I've created a pull request #15

**Comment by DaveVdE** [comment]
I have the `RoleClaimType` set to `roles` in my `Startup.Auth.cs`, but at the point of testing if the user is in that specific role the `RoleClaimType` on the `ClaimsIdentity` is set to the default. Any idea why?

**Comment by nezoic** [comment]
I too am having this same issue, User.IsInRole never sees the Role claim as valid even though it's in the list of claims.

http://stackoverflow.com/questions/36487458/azure-ad-returning-roles-in-claims-but-user-isinrole-returns-false

**Comment by DaveVdE** [comment]
Yeah it works for me, I don't remember what caused me to place the earlier comment.

**Comment by DaveVdE** [comment]
Sounds like you have a problem similar to what I was having: indeed we map the correct claims type, but it got overridden somehow on my end. 

Problem is, that's some while ago and I can't find anything in source control on how I fixed that.

**Comment by euhm** [comment]
Hi @DaveVdE, I have the same issue like you had. The RoleClaimType is always reverted to the default.
So the value set in TokenValidationParameters is never picked up.

Maybe you remember now how you fixed at your end?

kind regards

**Comment by DaveVdE** [comment]
Nope, sorry.

I also switched employer, so I have no longer access to that source code.

**Comment by jmprieur** [comment]
This now seems to work correctly (I've proposed PR[#24: Improving the Readme.md file (clarifies confusing points, makes it work with VS>2013, simplifies the end to end) ](https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims/pull/24) to improve the Readme.md and the code in `Startup.Auth.cs`

**Comment by jmprieur** [comment]
Closing the issue as I believe this is now working correctly. Feel free to re-open if you disagree.
