### ISSUE TITLE
Unable to assign roles

### ISSUE THREAD

**Issue by shaneholder** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#16]
I'm sure this isn't an issue with the app itself but I am unable to assign roles to users in either of the Azure management portal.  I am using the Azure services with my MSDN subscription.  Is RBAC only available with an enterprise subscription?

**Comment by shaneholder** [comment]
I think I figured it out.  I had configured an active directory with the B2C directory preview and assigned the example application to that directory.  Also once I navigated that B2C directory the portal thinks applications configured under non B2C directories have the same attributres so they do not the User management tabs until you refresh the browser.

**Comment by dotnetdude** [comment]
Hi, I got the same issue. Looks like its a bug on chrome browser. I can see user management tab on all other browsers and not in chrome. As you suggested, the refresh trick worked.

**Comment by jmprieur** [comment]
I just tried with chrome Version 56.0.2924.76 (64-bit) on https://manage.windowsazure.com and that seems to work now.
