### ISSUE TITLE
Invalid client secret error on Azure App Service

### ISSUE THREAD

**Issue by vkurpad** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#19]
Works fine locally. I'm able to see the role assignments come through. But Can't get the app to log in a user when deployed to Azure. 

Errors out with message: 
AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided. Trace ID: f2dd722f-1017-4d28-92a9-1a243c62f020 Correlation ID: 3b525670-3b61-4f08-9e5b-410312813ac2 Timestamp: 2016-02-15 15:05:20Z

**Comment by dstrockis** [comment]
Sounds like there's something strange going on with the parsing of your app key.  You'll need to somehow validate that the string being provided to the `AcquireTokenByAuthorizationCode` is in fact your client secret.

But actually now that I take a closer look, I don't think this sample requires you to even acquire a token.  That's a bug on my part.  I think if you just remove the line(s) of code in `Startup.Auth.cs` that do the token acquisition (and throw the error) you should find the sample works for you.

**Comment by vkurpad** [comment]
Danny thanks for the response. I'm still not any closer to getting it to work. could you post a snippet of the change you're recommending?

**Comment by mcorning** [comment]
Danny, I agree that your suggestions are either not clear enough for us to implement correctly, or they are inadequate to resolve the issue.
Is there a reason that the sample shipping today (Sep 2016) is not debugged?
for the record, I commented out these lines in the web app's startup file:
                Events = new OpenIdConnectEvents
                {
                    //OnRemoteFailure = OnAuthenticationFailed,
                    //OnAuthorizationCodeReceived = OnAuthorizationCodeReceived,
                }
also, when I try to login or click the ToDoList link, I get the kind of error msg that used to drive BillG nuts: "An error occurred while processing your request." further, the error page suggest I set the development environment, but that setting is there by default.

**Comment by jmprieur** [comment]
@mcorning, can you please try with the updated sample? Closing this issue for now as I believed this is fixed. Feel free to reopen if that does not work for you.

**Comment by ddobric** [comment]
I'm also getting this error very often. I always thought, it was my failure by copy/paste. However, it happens sometimes by some keys. I never understood when and how. It looks like some encoding issue. I usually in this case generate next key (usually multiple times) until it works.

**Comment by bcoder0306** [comment]
Just had this happen. I had generated two client secrets which failed as described above. Then generated a third secret which succeeded. I noticed that the 2 keys that failed both had / and + in the string. The one that worked and only alpha-numeric characters. Perhaps this will provide a clue. It does seem like a bug to me.

**Comment by ergwun** [comment]
Thanks bcoder0306 - I couldn't get my app to authenticate either. After reading your post I kept generating keys until I had one without + or / and it finally worked!

**Comment by DivyansMahansaria** [comment]
without + or / worked for me as well. Thanks a ton!

**Comment by mcsf13m036** [comment]
Try encoding only your client secret key.

**Comment by nothingisnecessary** [comment]
Noticed same problem with the keys - only about 30% of my generated keys worked. One that did work contained / but no +. For the most part the keys that have / and + seem to cause problems, but that may just be coincidence. Tried with various encodings to create the byte array (ASCII, UTF8, Unicode) but still get "invalid client secret is provided" until I use a working key. In Postman, 100% of the keys work, but coming from .NET only about 30% of them worked.. possible bug in the .net web client? Must ILSpy and explore further..

**Comment by nothingisnecessary** [comment]
mcsf13m036 is correct: you need to encode the key. If key doesn't contain the + character it generally seems to work OK, but 100% of tested keys now work after I properly URI encode the client_secret value. To wit: `Uri.EscapeDataString(clientSecret)`

**Comment by arnaringig** [comment]
As suggested above, try and encode your symbols so for instance + becomes %2B
Worked for me.

**Comment by vivekrathi8993** [comment]
keys without '+'s works <3 thanks

**Comment by bgarcial** [comment]
Hi everyone.
I got the same error, here 
```
2019-10-27T12:33:51.9093106Z Deployment name is AzureDevOpsDeployment_60
2019-10-27T12:33:58.6518411Z There were errors in your deployment. Error code: InvalidTemplateDeployment.
2019-10-27T12:33:58.6524365Z ##[error]The template deployment 'AzureDevOpsDeployment_60' is not valid according to the validation procedure. The tracking id is '8a98bf25-faa0-4454-b99a-4da3ae9b66da'. See inner errors for details.
2019-10-27T12:33:58.6530993Z ##[error]Details:
2019-10-27T12:33:58.6560196Z ##[error]BadRequest: Provisioning of resource(s) for container service Service-aks in resource group development failed. Message: {
  "code": "BadRequest",
  "message": "Service principal client secret has invalid characters: ` '",
  "target": "servicePrincipalProfile.secret"
 }. Details: 
2019-10-27T12:33:58.6561600Z ##[error]Task failed while creating or updating the template deployment.
2019-10-27T12:33:58.6587223Z ##[section]Finishing: Azure Deployment:Create Or Update Resource Group action on development
```
I tried to regenerate my service principal secret, but nothing change.
How can I encode the symbols in the secret sting, such as @mcsf13m036, @nothingisnecessary  and @arnaringig  suggest?

**Comment by kalyankrishna1** [comment]
Use 

[Uri.EscapeDataString(clientSecret)](https://docs.microsoft.com/en-us/dotnet/api/system.uri.escapedatastring?view=netframework-4.8)
[Uri.UnEscapeDataString(clientSecret)](https://docs.microsoft.com/en-us/dotnet/api/system.uri.unescapedatastring?view=netframework-4.8)

**Comment by bajaj689** [comment]
I have setup a python web application which authenticates and authorizes through Azure AD. My client secret has special characters like = equals, ? question mark,  - dash , _ underscore. There is no + sign or / sign.   I get the error : 
_invalid_client AADSTS7000222: The provided client secret keys are expired.  And sometimes I get the error as invalid client secret key. here is what I tried already:_

1) Tried to regenerate a new secret and use it.
2) url encoded the client secret before being sent to Azure AD  using the urllib.parse.quote function
Here what I couldnt understand is that even if my web app sends encoded secret, the azure AD will compare the secret stored with it without decoding my secret. So obviously the response will say invalid secret. I guess we cant enforce Azure AD to decode it.

Please share your views @mcsf13m036, @nothingisnecessary and @arnaringig
