### ISSUE TITLE
Role Claims not emitted for Guest Accounts

### ISSUE THREAD

**Issue by dstrockis** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#2]
Temporary shortcoming.

**Comment by onovotny** [comment]
Ping, has this been resolved; can this issue be closed?

**Comment by jmprieur** [comment]
Fixed

**Comment by jangaehler** [comment]
The readme says:
> NOTE: Role claims are not currently emitted for guest users in a tenant (see issue #2).
Sorry, i'm confussed now. Is this fixed or not?
