### ISSUE TITLE
Can't get roles to work with newer versions of Tokens.JWT

### ISSUE THREAD

**Issue by gpalsson** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#21]
If I update to anything never than 4.0.2.28 the test application will stop pulling roles from the AD.
I wonder if this is this an issue with JWT, this app or my Azure AD ?

**Comment by x3r10n** [comment]
@gpalsson Wow you just saved my life !! I wasted 2 days trying to figure what was wrong between my app and this boilerplate. But a BIG thumb down to Microsoft for not posting back any information on that issue.
Once again Thanks @gpalsson !!

**Comment by jmprieur** [comment]
@x3r10n, @gpalsson, thanks for the feedback: 
I just tried upgrading the JWT NuGet package from 4.0.2.202250711 (proposed in the sample) to 4.0.3.308261200 and, although I can log-in, I cannot access the Tasks. I get: 
*You do not have sufficient priviliges to view this page.*

**Comment by spegase** [comment]
If anyone knows how to fix this...

**Comment by RehanSaeed** [comment]
I'm using ASP.NET Core and am not getting any roles back in my users claims collection. Are there any workarounds or solutions to this problem?

**Comment by gpalsson** [comment]
@jmprieur try listing what roles you are part of once you have logged in. If you have configured your user with some roles, you should be able to see them.

@x3r10n no problem, I'm glad it was helpful.

**Comment by fwwasol** [comment]
I had the same issue and found not claims with type "role" or "roles". 
But this worked: 

`                    TokenValidationParameters = 
                    new System.IdentityModel.Tokens.TokenValidationParameters
                    {
                        ValidateIssuer = false,
                        RoleClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                    },
`

**Comment by dotsad** [comment]
@fwwasol it would be nice if you specified where you added this code.

**Comment by kalyankrishna1** [comment]
The upgraded solution is in with the latest token validation lib.

<package id="System.IdentityModel.Tokens.Jwt" version="5.2.4" targetFramework="net461" />
