### ISSUE TITLE
Does appRoles support transitive groups? appRole=>Group1HasMember=>Group2

### ISSUE THREAD

**Issue by belaie** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#22]
Does appRoles support transitive groups? appRole=>Group1HasMember=>Group2

Will members og Group2 would also get the appRole assigned to Group1?

**Comment by gsacavdm** [comment]
No, Azure AD in general has very limited support for nested groups. This limitation also applies for appRole assignments.

**Comment by RehanSaeed** [comment]
Firstly, thank you!

I stumbled on this after 3 hours of trying to understand why my roles were not appearing. I can't believe something so basic has not been implemented. I've raised a suggestion on [UserVoice](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/18678670-support-inheriting-roles-in-nested-groups) to implement this feature. Please upvote it.
