### ISSUE TITLE
Manifest error in sample code with single-tenant

### ISSUE THREAD

**Issue by sameer-kumar** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#23]
While following your sample code for single-tenant flow path, I get error while updating the manifest with suggested roles. It poops out at line `"origin": "Application",` And if I yank this line from json manifest, it works and able to upload.

Another concern is how can I add groups to roles instead of individual users in azure management portal? When I goto USERS tab of my application, it displays all existing AAD users, but not groups neither there is an option to add a new group and assign application role. 

Am I missing something?

Thanks!

**Comment by jmprieur** [comment]
@sameer-kumar: I've updated the Readme.md file. Please tell me if you are happy for me to close this issue.
As far as adding groups (and not only users) to roles this is a feature of Azure AD premium.

**Comment by sameer-kumar** [comment]
Yes, you can go ahead and close this. Thanks for taking care of this and your answer!

**Comment by sameer-kumar** [comment]
And I hope faster turn-around times in future :-)

**Comment by jmprieur** [comment]
@sameer-kumar : I'm trying to improve all the .NET client samples at the moment. Don't hesitate to contact me directly to draw my attention to pressing issues (there are many samples, some with many problems. I'm happy to priorise the work based on needs.
