### ISSUE TITLE
this sample need updates!

### ISSUE THREAD

**Issue by spegase** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#25]
1. The property "origin" don't exist anymore like said in the issue#23
2. The roles are not working since weeks as mentioned in the issue#21
3. The sample here lack clarity and is outdated.

Microsoft seriously how do you think we can keep up with serious products and services when the specifications change all the time and features are removed without warnings.

**Comment by jmprieur** [comment]
Thanks for your feedback @spegase. I've just done a first update to the sample as this will help already (BTW this resolves issue#23)

**Comment by jmprieur** [comment]
Oh, also I'll look at the root cause for issue#21, which I can repro as well.

**Comment by spegase** [comment]
Hi @jmprieur  thanks for the fixes, when will you push them?

**Comment by jmprieur** [comment]
@spegase: do you mean for issue#21? If yes, I can repro but need to investigate what is going on.
