### ISSUE TITLE
Directory Object Not Found.

### ISSUE THREAD

**Issue by twcarnahan** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#26]
I have logged on as Admin --- I can create tasks, but when I click on "About" I get the Directory Object Not Found; when I click on "Search for Users/Groups:" Error searching directory.
Thank you for your help with this problem.

I can logon as a Non- Admin --- and then get of course denied. So, I do not understand what is wrong. Tim:

**Comment by kalyankrishna1** [comment]
Please try this again with the updated sample and reopen this issue if it still exists. Thanks
