### ISSUE TITLE
Not able to set Microsoft Graph permissions

### ISSUE THREAD

**Issue by AmanpreetSingh-GitHub** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#27]
I created a new Azure subscription (free) and under the Default directory registered a new Cloud Service ASP.Net MVC Web Application. I also added a new user to the default domain. When I run the application everything works in the application connected with this Azure AD.
Now when I try to set permissions for Microsoft Graph I see no permissions there. And thats why my User.IsInRole and IsAuthenticated doesn't work.
Can you help ?
![error](https://cloud.githubusercontent.com/assets/16236053/24142649/2de0ae54-0e4d-11e7-87c4-e0bb79d82a66.PNG)

**Comment by aadidgit** [comment]
Is the user an AzureAD administrator (in Azure Active directory, choose a user, and go to "Directory Role")

**Comment by AmanpreetSingh-GitHub** [comment]
Yes, both the users are Global Administrators.
User 1 (amanpreet.singh@hotmail.com) - this created the free subscription
User 2 (amanpsingh@amanpreetsinghhotmail.onmicrosoft.com) - added by User 1

**Comment by jmprieur** [comment]
I has a similar problem. I managed to have the "Microsoft Graph" service principal added to my subscription by navigating to the graph explorer (https://developer.microsoft.com/en-us/graph/graph-explorer), signing-in as one of the administrator and accepting the consent to access the graph.
HTH

**Comment by kalyankrishna1** [comment]
This sometimes happen due to transient issues. If this issue still persists, please reopen this issue.
