### ISSUE TITLE
Is it possible to activate '.auth/me' endpoint?

### ISSUE THREAD

**Issue by paolorr** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#29]
I activated AAD authentication through the portal (along with FB and Twitter auth), as shown in [this tutorial](https://docs.microsoft.com/en-us/azure/app-service-web/web-sites-dotnet-lob-application-azure-ad),  and there's the option to view the user info at '.auth/me' endpoint, which is automatically created.
Activating AAD authentication in the application, like in this sample, Im not able to reach this endpoint, since it's created by App Service Authentication / Authorization. Is this possible to turn it on?

**Comment by kalyankrishna1** [comment]
@paolorr , please post this as an issue in the EasyAuth sample. The link is https://github.com/stuartleeks/AzureFunctionsEasyAuth. Thanks
