### ISSUE TITLE
can we use  (https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims) Azure AD role based authorization for B2C tenant

### ISSUE THREAD

**Issue by vishwajeetrkale** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#34]
can we use  (https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims) Azure AD role based authorization for B2C tenant ?

**Comment by kalyankrishna1** [comment]
No, Please go through this (https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/31997947-support-application-specific-roles-in-b2c)
