### ISSUE TITLE
Bad Request - Request Too Long

### ISSUE THREAD

**Issue by mqamarmunir** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#35]
Sometimes while signing In,the application fails to redirect to my home page and the following page shows up. 
![image](https://user-images.githubusercontent.com/4126664/40780501-01048048-64f2-11e8-9a29-19cc7bc44704.png)

Then I am stuck, not able to log out or sign in again. is there any workaround for this?

**Comment by jmprieur** [comment]
This is probably because you have too many roles? 
You might want to have a look at the request with Fiddler to understand why it's too long?

**Comment by mqamarmunir** [comment]
added following line in my global.asax file and it started working
`protected void Session_Start() { }`
I don't  know how, but at least it started working. The solution was mentioned in the following thread.
[#2496](https://github.com/IdentityServer/IdentityServer3/issues/2496)
I would be glad if you could provide some explanation for this behavior

**Comment by jmprieur** [comment]
@brentschmaltz : do you understand why adding an override of Session_Start() avoids the Request too long?

**Comment by kalyankrishna1** [comment]
The browsers sometime do this and can be resolved by clearing cookies. If it still persists, please re-open this issue.
