### ISSUE TITLE
TasksController is not working as the Views>Tasks>Index.cshtml has issues. Isn't that name be "Tasks.cshtml"?

### ISSUE THREAD

**Issue by Srinuthalapati** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#37]
![image](https://user-images.githubusercontent.com/23491817/42605536-485b0240-852d-11e8-85f9-0de78c5ad349.png)
when clicked on 'Tasks' tab, the actual functionality to test RBAC should appear. But the below error is shown:
![image](https://user-images.githubusercontent.com/23491817/42605488-01e25d7c-852d-11e8-9bdc-9139aadff5c8.png)

**Comment by Srinuthalapati** [comment]
Can I expect a solution or a suggestion regarding this issue?

**Comment by kalyankrishna1** [comment]
No , its asp.net route and it works as indicated. Please enable logging in your azure website and check for the error underneath.

**Comment by jmprieur** [comment]
This sample was recently updated. I've just tested it again and it works. Closing this issue. Feel free to reopen .
