### ISSUE TITLE
IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null

### ISSUE THREAD

**Issue by mqamarmunir** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#42]
Some times after successful login the following error shows up

> IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'.
![image](https://user-images.githubusercontent.com/4126664/46532417-27ae3280-c8ba-11e8-9292-b156800fae26.png)

**Comment by kalyankrishna1** [comment]
@mqamarmunir  this issue and its possible solutions have been discussed in quite a bit of detail in the this thread https://stackoverflow.com/questions/39412570/owin-openidconnect-middleware-idx10311-nonce-cannot-be-validated. Please have a look at it.

**Comment by mqamarmunir** [comment]
@kalyankrishna1 
Thanks for the reply
Switching to the previous version help me get out of it. But that is not the permanent fix. What do you say?

**Comment by kalyankrishna1** [comment]
cross posted to the correct repository
