### ISSUE TITLE
Sample for Microsoft.NETCore.App 2.1.0 SDK?

### ISSUE THREAD

**Issue by snpdev** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#43]
Does anyone know if there is a fork of this sample application for the Microsoft.NETCore.App 2.1.0 SDK (or other .NET Core version)?

**Comment by kalyankrishna1** [comment]
This sample just adds a tiny bit of code in the standard asp.net core project generated by VS.NET. You can create a new project, use a diff tool to find the code changes and copy it in your own project

**Comment by jmprieur** [comment]
Please have a look at https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-1-Roles, which ise ASP.NET Core 2.2 for the moment.
