### ISSUE TITLE
Click the "All Applications" tab, and locate the newly created entry for "WebApp-RoleClaims-DotNet"

### ISSUE THREAD

**Issue by aai2on** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#44]
After creating TaskTrackerWebApp-RoleClaims and doing the following steps, I went into Enterprise applications and select All Applications and I do not see WebApp-RoleClaims-DotNet,  I find the name with TaskTracker in the front.  Is this what you meant? Or was there a step for creating another application for WebApop-RoleClaims-DotNet that I missed.  I looked but don't see it.

**Comment by jmprieur** [comment]
you should not go to Enterprise applications, but to **Azure Active Directory** and the **App registrations**

**Comment by jmprieur** [comment]
@kalyankrishna1
