### ISSUE TITLE
AntiForgeryToken causes Exception

### ISSUE THREAD

**Issue by hauszerm** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#47]
I want to use AntiForgeryToken and added the Attribute [ValidateAntiForeryToken] in the TaskController

       
        [HttpPost]

        [Authorize(Roles = "Admin, Writer, Approver")]

        [ValidateAntiForgeryToken]

        public ActionResult TaskSubmit(FormCollection formCollection)

        {
        .....

and the @Html.AntiForgeryToken() in the View 

 
     using (Html.BeginForm("TaskSubmit", "Tasks", FormMethod.Post))

    {

        @Html.AntiForgeryToken()

        <div class="container" style="padding-top:10px">

            <div class="row">
       ....

Unfortunately I get a _System.InvalidOperationException: 'A claim of type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress' was not present on the provided ClaimsIdentity.'_
I have spent some hours to investigate this exception and to find some useful hints, how to aolve this issue.

The found a most poopular hint to add this line  in the global.asax.cs ApplicationStart(), but it did not work

`
            AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.Email;
`

I have 22 claims and one claim is "**email: my mail address**".

Any hints and suggestions solving my problem are welcome, Michael

**Comment by jmprieur** [comment]
@hauszerm : you might want to check https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims ?

**Comment by kalyankrishna1** [comment]
@hauszerm , did adding the optional emailaddress claim solve your issue?

**Comment by kalyankrishna1** [comment]
Closing this as we have not received any response
