### ISSUE TITLE
Question: How to add Fine Grain permissions to this example?

### ISSUE THREAD

**Issue by tiny-dancer** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#48]
We are investigating Azure AD for our usage and love your example! Have a question on how to take this example from course level permissions to fine grain: 

> **Admin**: Has the ability to perform all actions, as well as manage the Application Roles.
**Writer**: Has the ability to create tasks.
**Approver**: Has the ability to change the status of tasks.
**Observer**: Only has the ability to view tasks and their statuses.

Right now this example consists of Course Grain permissions, ie. if your an `Admin`, `Approver`, or `Observer`, you have that access across _all_ tasks.  How could Azure AD be utilized to provide these access levels on each individual task (ie. resource)?

For example:
- User 1 could be assigned as an `Approver` for Task 1 but not Task 2
- Group 1 could be assigned as an `Approver` for Task 1 but not Task 2
- All `Writer`'s are authorized `Observer` access to their created tasks

Coming from Keycloak usage, implementation references would be:
- [Resource-based permissions](https://www.keycloak.org/docs/5.0/authorization_services/#_permission_create_resource)
or 
- [User-Managed Access (UMA 2.0)](https://www.keycloak.org/docs/5.0/authorization_services/#_service_user_managed_access)

Thanks!

**Comment by tiny-dancer** [comment]
Based on response in other post (https://github.com/Azure-Samples/active-directory-dotnet-webapp-roleclaims/issues/49), doing fine grain permissions is not possible in Azure AD?

- **Fine Grain Permissions**: each data item is given its own access control policy.

**Comment by kalyankrishna1** [comment]
Its on the roadmap, but not available yet. Not ETAs to share either .
