### ISSUE TITLE
Question: How to perform permission-based authorization with Roles?

### ISSUE THREAD

**Issue by tiny-dancer** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#49]
A fundamental approach in programming authorization logic in applications for long term stability and reliability is to focus on `permissions` and not `roles` or `groups` within the code itself.

The reasoning for this is portrayed excellently by this [SO post](https://softwareengineering.stackexchange.com/questions/299729/role-vs-permission-based-access-control), displayed here readability:

> At the moment of checking, the calling code only needs to know "does user X have permission to perform action Y?".
The calling code does not care about and should not be aware of relationships between roles and permissions.
> 
> The authorization layer will then check if the user has this permission, typically by checking if the user's role has this permission. This allows you to change authorization logic without updating the calling code.
> 
> If you directly check for role at the call site, you are implicitly forming role ⇄ permission relationships and injecting authorization logic into the calling code, violating separation of concerns.
> 
> Should you later decide that role `foo` should not have permission `baz`, you would have to change every code which checks if the user is a `foo`.  

In the primary authorization examples in Github for Azure AD I see good integration with `Groups` and `Roles`:

```c#
[Authorize(Roles = "Admin, Writer, Approver")]
public ActionResult TaskSubmit(FormCollection formCollection)
{
  if (User.IsInRole("Admin") || User.IsInRole("Writer"))
  ...
{
```

However there doesn't appear to be an example for `Permissions`.  In this space, one would expect the ability to do (with a [custom handler](https://stackoverflow.com/a/36447358/3841838)):

```c#
[Authorize(Policy = "task.submit")]
public ActionResult TaskSubmit(FormCollection formCollection)
{
    ...
}
```

Under the covers, `[Authorize(Policy = "task.submit")]` would call Azure AD to verify if the user has the `task.submit` permission.  Azure AD would evaluate this internally through the users `Groups` and `Roles` and their access to the `task.submit` permission in the application configuration.

In this approach, the below changes (and more) could go into enforcement without requiring a code change:
- Permission changes to `Admin` and `Writer` removing their ability to submit tasks
- Assigning a `Group` permissions to submit tasks
- Assigning a new role with permission to submit tasks  

Scopes

At first glance, [Scopes](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#scopes-and-permissions) appeared to provide these `Permissions` however it appears they are only usable in application to application.  `Users`, `Groups`, or `Roles` cannot be assigned to a `scope`, and when an application requests a `scope` all users using the application receive that permission.

Is there the ability to do the above permission-based access with Azure AD? 

Thanks!

Additional References:
- [Keycloak Permission](https://www.keycloak.org/docs/5.0/authorization_services/#permission)
- [A better way to handle role permissions in ASP.NET Identity – IsInRole vs. HasPermission](http://odetodata.com/2015/05/a-better-way-to-handle-role-permissions-in-asp-net-identity-isinrole-vs-haspermission/)
- [SO: How to implement Permission Based Access Control with Asp.Net Core](https://stackoverflow.com/a/36447358/3841838)

**Comment by tiny-dancer** [comment]
The [Admin Role Permissions](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#role-permissions) page  appears to be outlined in this fashion. For example, a user performing the action (permission) of `microsoft.aad.directory/applications/audience/update` would be granted access having either of the `Application Administrator` or `Cloud Application Administrator` roles.

**Comment by kalyankrishna1** [comment]
@tiny-dancer , the page you have provided is used by the Azure Service Management to implement Azure RBAC. Azure AD provides options to provide permissions using Scopes, that travel in the 'scp' claim. Currently we have an open ask to allow users to provide deeper permissions , like one or more security groups instead of "Groups.Read.All" or name of the actual Sharepoint sites over "Sites.ReadWrite.All". Its something we are considering, but we do not have an ETA for this.

**Comment by jmprieur** [comment]
If are building your own API, @tiny-dancer : I suggest you have a look at this sample:https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore (it explains how to define scopes)

**Comment by tiny-dancer** [comment]
@jmprieur @kalyankrishna1 thank you for your responses and thanks in advance for helping clarify Azure AD's current capabilities.

This is indeed related to using Azure AD for authorization of our own APIs. 
 Based on your responses, **Azure AD does not support permission-based authorization** and uses Scopes (application) and Roles (users) for authorization.  

Extending the example provided, https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore by adding the requirement to limit those (applications and users) who can create tasks.  Is the below an accurate implementation of adding this requirement?  Am I missing Azure AD features?  

### Scopes

We start by adding the below scope:

TodoListService
- `Tasks.Create`

And updating the code to add `Authorize`, similar to:

```C#
// POST api/values
[Authorize(Policy = "Tasks.Create")]
[HttpPost]
public void Post([FromBody]TodoItem Todo)
{
      string owner = (User.FindFirst(ClaimTypes.NameIdentifier))?.Value;
      todoStore.Add(new TodoItem { Owner = owner, Title = Todo.Title });
}
```


- **Applications**: 👍 We successfully now have a way to limit which applications have access to create tasks.  A consuming application will need to explicity request the `Tasks.Create` scope, such as TodoListClient.
- **Users**: 👎 We are not able to limit which users have access to create tasks, *every* user that logs into the TodoListClient application will have access to create tasks, as every user inherits that application's `Task.Create` access.

### Roles

To limit which users have task create access our only other Azure AD options would be roles with `allowedMemberTypes` of `User`.  

We update the code similar to (psuedo):
```C#
// POST api/values
[Authorize(Policy = "Tasks.Create")] or [Authorize(Roles = "TaskMaster")]
[HttpPost]
public void Post([FromBody]TodoItem Todo)
{
      string owner = (User.FindFirst(ClaimTypes.NameIdentifier))?.Value;
      todoStore.Add(new TodoItem { Owner = owner, Title = Todo.Title });
}
```

- **Users**: 👍 By explicity assigning users or groups to the defined `TaskMaster` role we can limit which users can create tasks.  

### Summary

👎 Using Roles leads us back to the OP and the downsides of implementing Role based authorization in code.  This downside is further cemented by the fact that Azure Service Management's RBAC itself does not follow this implementation, instead authorizing against `Actions` and not directly against the `Roles`. Additionally it means the code will need different authorization logic between **Applications** and **Users**.
 

Thanks again!

**Comment by maurert** [comment]
I have exactly the same question. I would like to implement permission based authorization in my Applications and API's and be able to assign these permissions to roles that can be created dynamically. 

Looks like competitors have had these features for some time. For example:
https://auth0.com/docs/authorization/concepts/rbac
https://auth0.com/docs/dashboard/guides/users/assign-permissions-users

I am also interested of the second issue you describe. Be able to assign permission to specific resources. For now it looks like I need to implement this in my own service instead of using AAD.

Are there any news regarding these features?

@tiny-dancer Did you find any good workarounds?
