### ISSUE TITLE
Question: How to use graphapi in this case  ?

### ISSUE THREAD

**Issue by kbula1** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#51]
Nice example, but I have a question. You wrote that assignment of users through Microsoft Graph API. I have searched Graph API URLs or examples for a whole day and I did not find an example. My goal is to search all users from my application and then change roles by Graph API. I will be very grateful If you could help me eg. paste URLs from GRAP API or write where I should search.

Thanks!

**Comment by TiagoBrenck** [comment]
Hello, 

The URL to get all the users would be: `https://graph.microsoft.com/v1.0/users` 
To request is, you will have to send a bearer token on the HTTP Header, with the scope "user.readbasic.all".
For the role scenario, you might be looking in two operations: Add new member to a role, and delete a member from a role.

Check the URLs here: https://docs.microsoft.com/en-us/graph/api/resources/directoryrole?view=graph-rest-1.0

**Comment by kalyankrishna1** [comment]
Or if its assignment to approles, you might be needing the following Api
https://docs.microsoft.com/en-us/graph/api/approleassignment-update?view=graph-rest-beta&tabs=cs

**Comment by kbula1** [comment]
Thanks for the answer ! @kalyankrishna1  I used API from the link but it has not worked for me. I have BadRequest (Write requests are only supported on contained entities).
Only GET action is working, But PATCH and DELETE not (example below). I know that is beta still... 
Have you any idea?
 
### Working
GET https://graph.microsoft.com/beta/servicePrincipals/{{objectId}}/appRoleAssignments
content-type: application/json
Authorization: Bearer {{token}}


### NOT WORKING
PATCH https://graph.microsoft.com/beta/servicePrincipals/{{objectId}}/appRoleAssignments
Content-type: application/json
Authorization: Bearer {{token}}

{
  "creationTimestamp": "2016-10-19T10:37:00Z",
  "principalDisplayName": "userdisplayname",
  "principalId": "40979666-6369-42e8-9d10-efa3b6ef9529",
  "principalType": "User",
  "resourceDisplayName": "MyAppName",
  "resourceId": "66ec05bf-4e41-4cd9-99f9-fe2f576b17dc"
}

Error : 

{
  "error": {
    "code": "BadRequest",
    "message": "Write requests are only supported on contained entities",
    "innerError": {
      "request-id": "910d4c08-ee18-4152-90a4-8541495d1bf7",
      "date": "2019-05-10T08:03:49"
    }
  }
}

**Comment by kalyankrishna1** [comment]
A little short on time to look into this in detail. My advice is to try the PowerShell commands in [this ](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/5-WebApp-AuthZ/5-1-Roles/README.md) sample and capture the calls in Fiddler. (enable https capture). 

The PowerShell commands call Graph behind the scenes, and in the capture you can see the syntax of the api. 

See the section "You can also use PowerShell scripts that automatically creates these two roles for your app" in the sample's readme. The scripts will be in the "[AppCreationScripts](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/5-WebApp-AuthZ/5-1-Roles/AppCreationScripts)" folder.
