### ISSUE TITLE
Authorize attribute not working

### ISSUE THREAD

**Issue by aamirrideo** [Azure-Samples/active-directory-dotnet-webapp-roleclaims#52]
I created this sample in my local and its authenticating fine, however when i deploy it to the Azure, although i am getting the claims, the Authorize attribute seems to not work and redirects me to the Authorization error page. I used the code to list the claims and i have them in the token.

P.S. The Active directory Authentication is enabled in Azure.

![Capture](https://user-images.githubusercontent.com/39773712/59066620-7a8f1e00-887d-11e9-927a-08307831b51d.PNG)

**Comment by jmprieur** [comment]
@aamirrideo : I would suggest you disable the App Service Authentication (code name Easy Auth). Your Web App already does the right thing, you don't need to add an additional layer of authentication.

cc: @kalyankrishna1 and  @SaeedAkhter-MSFT to comment out.
